#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-minitest-focus
Version  : 1.1.2
Release  : 4
URL      : https://rubygems.org/downloads/minitest-focus-1.1.2.gem
Source0  : https://rubygems.org/downloads/minitest-focus-1.1.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
= minitest-focus
home :: https://github.com/seattlerb/minitest-focus
rdoc :: http://docs.seattlerb.org/minitest-focus

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n minitest-focus-1.1.2
gem spec %{SOURCE0} -l --ruby > rubygem-minitest-focus.gemspec

%build
gem build rubygem-minitest-focus.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
minitest-focus-1.1.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/minitest-focus-1.1.2
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/minitest-focus-1.1.2.gem
/usr/lib64/ruby/gems/2.2.0/doc/minitest-focus-1.1.2/ri/MiniTest/Unit/TestCase/cdesc-TestCase.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-focus-1.1.2/ri/MiniTest/Unit/cdesc-Unit.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-focus-1.1.2/ri/MiniTest/cdesc-MiniTest.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-focus-1.1.2/ri/Minitest/Test/Focus/cdesc-Focus.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-focus-1.1.2/ri/Minitest/Test/cdesc-Test.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-focus-1.1.2/ri/Minitest/cdesc-Minitest.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-focus-1.1.2/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-focus-1.1.2/ri/page-History_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-focus-1.1.2/ri/page-Manifest_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-focus-1.1.2/ri/page-README_txt.ri
/usr/lib64/ruby/gems/2.2.0/gems/minitest-focus-1.1.2/.autotest
/usr/lib64/ruby/gems/2.2.0/gems/minitest-focus-1.1.2/.gemtest
/usr/lib64/ruby/gems/2.2.0/gems/minitest-focus-1.1.2/History.txt
/usr/lib64/ruby/gems/2.2.0/gems/minitest-focus-1.1.2/Manifest.txt
/usr/lib64/ruby/gems/2.2.0/gems/minitest-focus-1.1.2/README.txt
/usr/lib64/ruby/gems/2.2.0/gems/minitest-focus-1.1.2/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/minitest-focus-1.1.2/lib/minitest/focus.rb
/usr/lib64/ruby/gems/2.2.0/gems/minitest-focus-1.1.2/lib/minitest/focus4.rb
/usr/lib64/ruby/gems/2.2.0/gems/minitest-focus-1.1.2/lib/minitest/focus5.rb
/usr/lib64/ruby/gems/2.2.0/gems/minitest-focus-1.1.2/test/minitest/test_focus.rb
/usr/lib64/ruby/gems/2.2.0/specifications/minitest-focus-1.1.2.gemspec
